/**
 * 小程序端服务桥接
 * 直接引用 shared/src 的 mock 服务，用 wx.setStorageSync 做本地持久化
 */
const shared = require('../shared/src/index')

// 重新导出所有服务
export const {
  loginByPhone,
  registerCustomer,
  getCurrentUser,
  logout,
  getProducts,
  getProductById,
  getCategories,
  getOrders,
  getOrderById,
  createOrder,
  adjustOrderPrice,
  updateOrderStatus,
  cancelOrder,
  shipOrder,
  confirmBooking,
  getClerkOrders,
  getClerkOrderById,
  clerkShipOrder,
  getReturns,
  getReturnById,
  createReturn,
  reviewReturn,
  getCommissionRecords,
  getCommissionSummary,
  getSalesmanCustomers,
  getWithdrawalRecords,
  requestWithdrawal,
  requestWithdrawalByAmount,
  getCustomerById,
  getSalespersonById,
  bindSalesperson,
  submitVerification,
  saveAddress,
  deleteAddress,
  getSystemConfig,
  getUserNotifications,
  markNotificationRead,
  getUnreadCount,
  formatMoney,
  formatDate,
  formatDateTime,
  getOrderStatusText,
  getOrderStatusDesc,
  maskPhone,
  addToCart,
  getCartItems,
  clearCart,
} = shared
